# Generated by Django 5.1.4 on 2025-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customdocument", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="file_size",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
