# Generated by Django 5.1.4 on 2025-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customimage", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
