# Generated by Django 5.1.4 on 2025-01-25 11:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Name of the package", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Details about the package"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price for a single person",
                        max_digits=10,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days for the package",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="travel_packages"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_people",
                    models.PositiveIntegerField(help_text="Minimum group size"),
                ),
                (
                    "max_people",
                    models.PositiveIntegerField(help_text="Maximum group size"),
                ),
                (
                    "min_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum duration in days (optional)",
                        null=True,
                    ),
                ),
                (
                    "max_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum duration in days (optional)",
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for the specified group size and duration",
                        max_digits=10,
                    ),
                ),
                (
                    "package",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="travelpackage.travelpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person booking", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the person booking", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number of the person booking", max_length=15
                    ),
                ),
                (
                    "number_of_people",
                    models.PositiveIntegerField(
                        help_text="Number of people in the booking"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for the booking",
                        max_digits=10,
                    ),
                ),
                (
                    "booking_start_date",
                    models.DateField(help_text="Start date of the booking"),
                ),
                (
                    "booking_end_date",
                    models.DateField(help_text="End date of the booking"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="travelpackage.travelpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
