# Generated by Django 5.1.4 on 2025-01-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travelpackage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingrule",
            old_name="max_days",
            new_name="days",
        ),
        migrations.RemoveField(
            model_name="pricingrule",
            name="min_days",
        ),
    ]
