# Generated by Django 5.1.4 on 2025-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelpackage", "0002_rename_max_days_pricingrule_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="heading",
            field=models.CharField(blank=True, null=True),
        ),
    ]
