# Generated by Django 5.1.4 on 2025-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelpackage", "0003_pricingrule_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpackage",
            name="category",
            field=models.CharField(
                default="Spiritual", help_text="Category of the package", max_length=255
            ),
            preserve_default=False,
        ),
    ]
