# Generated by Django 5.1.4 on 2025-01-23 09:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customimage", "0003_customimage_description"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlepage",
            options={"verbose_name": "Article Page"},
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="rich_text",
        ),
        migrations.AddField(
            model_name="articlepage",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    ("article_section", 2),
                    ("contact_section", 14),
                    ("faq_section", 22),
                    ("feature_section", 31),
                    ("feature_row_section", 32),
                    ("hero_section", 34),
                    ("logo_cloud_section", 41),
                    ("team_section", 52),
                    ("testimonial_section", 59),
                    ("richtext_section", 60),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "From the blog",
                            "help_text": "Add a title",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Learn how to grow your business with our expert advice",
                            "help_text": "Add a description",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Ready To Take The Next Step?",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details. Keep it meaningful!",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write your address",
                            "label": "Location 1",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Country and district",
                            "label": "Location 2",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Number",
                            "label": "Phone Number",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write email",
                            "label": "Email",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Text",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://www.karnalijunglecamp.com",
                            "label": "Link",
                            "required": False,
                        },
                    ),
                    11: (
                        "main.blocks.helper_blocks.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("buttonn_type", 12),
                            ]
                        ],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 3),
                                ("description", 4),
                                ("location1", 5),
                                ("location2", 6),
                                ("phone", 7),
                                ("email", 8),
                                ("button", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a simply worded question, like 'How much will it cost?'",
                            "label": "Question",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Provide a short answer in no more than a few lines of text",
                            "label": "Answer",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("buttonn_type", 12),
                            ]
                        ],
                        {
                            "help_text": "Add a link to be followed for more information on that question, feature or product",
                            "label": "Button",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 17), ("answer", 18), ("button", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "FAQs"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("description", 16), ("faqs", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Why our product is best",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Unwind in Luxury, Explore the Wilderness",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the best of both worlds at our resort in Bardiya National Park. Enjoy comfortable accommodations paired with thrilling outdoor activities in a breathtaking natural setting.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    26: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Hero image", "required": False},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("buttonn_type", 12),
                            ]
                        ],
                        {"label": "Call To Action", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {"label": "Features"}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 23), ("features", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                                ("features", 30),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                            ]
                        ],
                        {"label": "Content", "required": True},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("content", 33)]], {}),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Our Partners",
                            "help_text": "Add a country name",
                            "label": "Country Name",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "We serve in 17 countries",
                            "help_text": "Add a description",
                            "label": "Logo Cloud Description",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Nepal",
                            "help_text": "Add a country name",
                            "label": "Logo Title",
                            "required": False,
                        },
                    ),
                    38: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the country logo",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 37), ("image", 38)]],
                        {},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"label": "Images"}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 35), ("description", 36), ("logos", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our illustrious leaders",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Here is a list of our Head Peeps. They look glorious rendered in HTML but are probably just normal, mortal humans.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": True},
                    ),
                    45: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Photo", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Role / Job Title",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Bio", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "LinkedIn Page", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Twitter Page", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 44),
                                ("image", 45),
                                ("role", 46),
                                ("description", 47),
                                ("linkedin", 48),
                                ("twitter", 49),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (50,),
                        {"label": "Team Members", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("description", 43), ("members", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our users love us. Look at these rave reviews...",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "deafult": "Traveller,CEO",
                            "help_text": "Job title of the person making the recommentation, if any",
                            "label": "Role",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (None, "No rating"),
                                (0, "0 Stars"),
                                (1, "1 Star"),
                                (2, "2 Stars"),
                                (3, "3 Stars"),
                                (4, "4 Stars"),
                                (5, "5 Stars"),
                            ],
                            "icon": "pick",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                                ("role", 55),
                                ("stars", 56),
                            ]
                        ],
                        {},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 53), ("description", 54), ("testimonials", 58)]],
                        {},
                    ),
                    60: ("wagtail.blocks.RichTextBlock", (), {}),
                },
                null=True,
                verbose_name="Content Section",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="customimage.customimage",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    ("article_section", 2),
                    ("contact_section", 14),
                    ("faq_section", 22),
                    ("feature_section", 31),
                    ("feature_row_section", 32),
                    ("hero_section", 34),
                    ("logo_cloud_section", 41),
                    ("team_section", 52),
                    ("testimonial_section", 59),
                    ("richtext_section", 60),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "From the blog",
                            "help_text": "Add a title",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Learn how to grow your business with our expert advice",
                            "help_text": "Add a description",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Ready To Take The Next Step?",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details. Keep it meaningful!",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write your address",
                            "label": "Location 1",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Country and district",
                            "label": "Location 2",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Number",
                            "label": "Phone Number",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write email",
                            "label": "Email",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Text",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://www.karnalijunglecamp.com",
                            "label": "Link",
                            "required": False,
                        },
                    ),
                    11: (
                        "main.blocks.helper_blocks.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("buttonn_type", 12),
                            ]
                        ],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 3),
                                ("description", 4),
                                ("location1", 5),
                                ("location2", 6),
                                ("phone", 7),
                                ("email", 8),
                                ("button", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a simply worded question, like 'How much will it cost?'",
                            "label": "Question",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Provide a short answer in no more than a few lines of text",
                            "label": "Answer",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("buttonn_type", 12),
                            ]
                        ],
                        {
                            "help_text": "Add a link to be followed for more information on that question, feature or product",
                            "label": "Button",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 17), ("answer", 18), ("button", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "FAQs"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("description", 16), ("faqs", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Why our product is best",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Unwind in Luxury, Explore the Wilderness",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the best of both worlds at our resort in Bardiya National Park. Enjoy comfortable accommodations paired with thrilling outdoor activities in a breathtaking natural setting.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    26: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Hero image", "required": False},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("buttonn_type", 12),
                            ]
                        ],
                        {"label": "Call To Action", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {"label": "Features"}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 23), ("features", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                                ("features", 30),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                            ]
                        ],
                        {"label": "Content", "required": True},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("content", 33)]], {}),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Our Partners",
                            "help_text": "Add a country name",
                            "label": "Country Name",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "We serve in 17 countries",
                            "help_text": "Add a description",
                            "label": "Logo Cloud Description",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Nepal",
                            "help_text": "Add a country name",
                            "label": "Logo Title",
                            "required": False,
                        },
                    ),
                    38: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the country logo",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 37), ("image", 38)]],
                        {},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"label": "Images"}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 35), ("description", 36), ("logos", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our illustrious leaders",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Here is a list of our Head Peeps. They look glorious rendered in HTML but are probably just normal, mortal humans.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": True},
                    ),
                    45: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Photo", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Role / Job Title",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Bio", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "LinkedIn Page", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Twitter Page", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 44),
                                ("image", 45),
                                ("role", 46),
                                ("description", 47),
                                ("linkedin", 48),
                                ("twitter", 49),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (50,),
                        {"label": "Team Members", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("description", 43), ("members", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our users love us. Look at these rave reviews...",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "deafult": "Traveller,CEO",
                            "help_text": "Job title of the person making the recommentation, if any",
                            "label": "Role",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (None, "No rating"),
                                (0, "0 Stars"),
                                (1, "1 Star"),
                                (2, "2 Stars"),
                                (3, "3 Stars"),
                                (4, "4 Stars"),
                                (5, "5 Stars"),
                            ],
                            "icon": "pick",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("images", 27),
                                ("button", 28),
                                ("role", 55),
                                ("stars", 56),
                            ]
                        ],
                        {},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 53), ("description", 54), ("testimonials", 58)]],
                        {},
                    ),
                    60: ("wagtail.blocks.RichTextBlock", (), {}),
                },
                null=True,
                verbose_name="Content Section",
            ),
        ),
    ]
