# Generated by Django 5.1.4 on 2025-01-24 12:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_articlepage_content_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    ("article_section", 2),
                    ("contact_section", 14),
                    ("faq_section", 22),
                    ("faq_image_section", 28),
                    ("feature_section", 30),
                    ("feature_row_section", 34),
                    ("feature_carousel_section", 37),
                    ("hero_section", 39),
                    ("hero_section_carousel", 39),
                    ("hero_slide_section", 39),
                    ("logo_cloud_section", 44),
                    ("richtext_section", 45),
                    ("team_section", 54),
                    ("testimonial_section", 59),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "From the blog",
                            "help_text": "Add a title",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Learn how to grow your business with our expert advice",
                            "help_text": "Add a description",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Ready To Take The Next Step?",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details. Keep it meaningful!",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write your address",
                            "label": "Location 1",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Country and district",
                            "label": "Location 2",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Number",
                            "label": "Phone Number",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write email",
                            "label": "Email",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Text",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    11: (
                        "main.blocks.helper_blocks.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("description", 4),
                                ("location1", 5),
                                ("location2", 6),
                                ("phone", 7),
                                ("email", 8),
                                ("button", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "We are the best", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the best of both worlds. Enjoy comfortable accommodations paired with thrilling outdoor activities in a breathtaking natural setting.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a simply worded question, like 'How much will it cost?'",
                            "label": "Question",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Provide a short answer in no more than a few lines of text",
                            "label": "Answer",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {
                            "help_text": "Add a link to be followed for more information on that question, feature or product",
                            "label": "Button",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 17), ("answer", 18), ("button", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "FAQs"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("faqs", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Lorem Ipsum Title", "required": False},
                    ),
                    24: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Hero image", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"label": "Call To Action", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 16),
                                ("image", 24),
                                ("button", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.ListBlock",
                        (26,),
                        {"label": "FAQs", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("faqs", 27)]],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (26,), {"label": "Features"}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("features", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details about your product. Keep it meaningful!",
                            "label": "Long Description",
                            "required": False,
                        },
                    ),
                    32: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the side panel of a feature list",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    33: ("wagtail.blocks.ListBlock", (26,), {"label": "Feature Rows"}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 16),
                                ("long_description", 31),
                                ("image", 32),
                                ("features", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("main.blocks.helper_blocks.APIImageChooserBlock", (), {}),
                    36: (
                        "wagtail.blocks.ListBlock",
                        (35,),
                        {"label": "Image Carousel"},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 16),
                                ("images", 36),
                                ("button", 25),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 16),
                                ("image", 24),
                                ("button", 25),
                            ]
                        ],
                        {"label": "Content", "required": True},
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("content", 38)]], {}),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Refobe LLC",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    41: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the country logo",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 16),
                                ("heading", 40),
                                ("image", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"label": "Images"}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("logos", 43)]],
                        {},
                    ),
                    45: ("wagtail.blocks.RichTextBlock", (), {}),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": True},
                    ),
                    47: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Photo", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Role / Job Title",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    49: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Bio", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "LinkedIn Page", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Twitter Page", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 46),
                                ("image", 47),
                                ("role", 48),
                                ("description", 49),
                                ("linkedin", 50),
                                ("twitter", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {"label": "Team Members", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("members", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "deafult": "Traveller,CEO",
                            "help_text": "Any subtitle realted to the person",
                            "label": "Role",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (None, "No rating"),
                                (0, "0 Stars"),
                                (1, "1 Star"),
                                (2, "2 Stars"),
                                (3, "3 Stars"),
                                (4, "4 Stars"),
                                (5, "5 Stars"),
                            ],
                            "icon": "pick",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 16),
                                ("image", 24),
                                ("button", 25),
                                ("role", 55),
                                ("stars", 56),
                            ]
                        ],
                        {},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("testimonials", 58)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Content Section",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    ("article_section", 2),
                    ("contact_section", 14),
                    ("faq_section", 22),
                    ("faq_image_section", 28),
                    ("feature_section", 30),
                    ("feature_row_section", 34),
                    ("feature_carousel_section", 37),
                    ("hero_section", 39),
                    ("hero_section_carousel", 39),
                    ("hero_slide_section", 39),
                    ("logo_cloud_section", 44),
                    ("richtext_section", 45),
                    ("team_section", 54),
                    ("testimonial_section", 59),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "From the blog",
                            "help_text": "Add a title",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Learn how to grow your business with our expert advice",
                            "help_text": "Add a description",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Ready To Take The Next Step?",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details. Keep it meaningful!",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write your address",
                            "label": "Location 1",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Country and district",
                            "label": "Location 2",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Number",
                            "label": "Phone Number",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write email",
                            "label": "Email",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Text",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    11: (
                        "main.blocks.helper_blocks.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("description", 4),
                                ("location1", 5),
                                ("location2", 6),
                                ("phone", 7),
                                ("email", 8),
                                ("button", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "We are the best", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the best of both worlds. Enjoy comfortable accommodations paired with thrilling outdoor activities in a breathtaking natural setting.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a simply worded question, like 'How much will it cost?'",
                            "label": "Question",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Provide a short answer in no more than a few lines of text",
                            "label": "Answer",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {
                            "help_text": "Add a link to be followed for more information on that question, feature or product",
                            "label": "Button",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 17), ("answer", 18), ("button", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "FAQs"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("faqs", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Lorem Ipsum Title", "required": False},
                    ),
                    24: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Hero image", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"label": "Call To Action", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 16),
                                ("image", 24),
                                ("button", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.ListBlock",
                        (26,),
                        {"label": "FAQs", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("faqs", 27)]],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (26,), {"label": "Features"}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("features", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details about your product. Keep it meaningful!",
                            "label": "Long Description",
                            "required": False,
                        },
                    ),
                    32: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the side panel of a feature list",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    33: ("wagtail.blocks.ListBlock", (26,), {"label": "Feature Rows"}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 16),
                                ("long_description", 31),
                                ("image", 32),
                                ("features", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("main.blocks.helper_blocks.APIImageChooserBlock", (), {}),
                    36: (
                        "wagtail.blocks.ListBlock",
                        (35,),
                        {"label": "Image Carousel"},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 16),
                                ("images", 36),
                                ("button", 25),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 16),
                                ("image", 24),
                                ("button", 25),
                            ]
                        ],
                        {"label": "Content", "required": True},
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("content", 38)]], {}),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Refobe LLC",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    41: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the country logo",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("description", 16),
                                ("heading", 40),
                                ("image", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"label": "Images"}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("logos", 43)]],
                        {},
                    ),
                    45: ("wagtail.blocks.RichTextBlock", (), {}),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": True},
                    ),
                    47: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Photo", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Role / Job Title",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    49: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Bio", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "LinkedIn Page", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Twitter Page", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 46),
                                ("image", 47),
                                ("role", 48),
                                ("description", 49),
                                ("linkedin", 50),
                                ("twitter", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {"label": "Team Members", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("members", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "deafult": "Traveller,CEO",
                            "help_text": "Any subtitle realted to the person",
                            "label": "Role",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (None, "No rating"),
                                (0, "0 Stars"),
                                (1, "1 Star"),
                                (2, "2 Stars"),
                                (3, "3 Stars"),
                                (4, "4 Stars"),
                                (5, "5 Stars"),
                            ],
                            "icon": "pick",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 16),
                                ("image", 24),
                                ("button", 25),
                                ("role", 55),
                                ("stars", 56),
                            ]
                        ],
                        {},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 16), ("testimonials", 58)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Content Section",
            ),
        ),
    ]
