# Generated by Django 5.1.4 on 2025-01-25 11:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_articlepage_content_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    ("article_section", 2),
                    ("contact_section", 14),
                    ("faq_section", 23),
                    ("faq_image_section", 30),
                    ("feature_section", 32),
                    ("feature_row_section", 36),
                    ("feature_carousel_section", 39),
                    ("hero_section", 41),
                    ("hero_section_carousel", 41),
                    ("hero_slide_section", 41),
                    ("logo_cloud_section", 46),
                    ("richtext_section", 47),
                    ("team_section", 56),
                    ("testimonial_section", 61),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "From the blog",
                            "help_text": "Add a title",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Learn how to grow your business with our expert advice",
                            "help_text": "Add a description",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Ready To Take The Next Step?",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details. Keep it meaningful!",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write your address",
                            "label": "Location 1",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Country and district",
                            "label": "Location 2",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Number",
                            "label": "Phone Number",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write email",
                            "label": "Email",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Text", "max_length": 100, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "If provided, the button will be a link to this URL",
                            "label": "Link",
                            "null": True,
                            "required": False,
                        },
                    ),
                    11: (
                        "main.blocks.helper_blocks.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("description", 4),
                                ("location1", 5),
                                ("location2", 6),
                                ("phone", 7),
                                ("email", 8),
                                ("button", 13),
                            ]
                        ],
                        {},
                    ),
                    15: ("main.blocks.common_blocks.TagsBlock", (), {"label": "Tag"}),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "We are the best", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the best of both worlds. Enjoy comfortable accommodations paired with thrilling outdoor activities in a breathtaking natural setting.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a simply worded question, like 'How much will it cost?'",
                            "label": "Question",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Provide a short answer in no more than a few lines of text",
                            "label": "Answer",
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {
                            "help_text": "Add a link to be followed for more information on that question, feature or product",
                            "label": "Button",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 18), ("answer", 19), ("button", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {"label": "FAQs"}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("faqs", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Debugging Tech and Staffing Glitches",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    26: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Hero image", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"label": "Call To Action", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("image", 26),
                                ("button", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {"label": "FAQs", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("faqs", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (28,), {"label": "Features"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("features", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details about your product. Keep it meaningful!",
                            "label": "Long Description",
                            "required": False,
                        },
                    ),
                    34: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the side panel of a feature list",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    35: ("wagtail.blocks.ListBlock", (28,), {"label": "Feature Rows"}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("long_description", 33),
                                ("image", 34),
                                ("features", 35),
                            ]
                        ],
                        {},
                    ),
                    37: ("main.blocks.helper_blocks.APIImageChooserBlock", (), {}),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {"label": "Image Carousel"},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("images", 38),
                                ("button", 27),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("image", 26),
                                ("button", 27),
                            ]
                        ],
                        {"label": "Content", "required": True},
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("content", 40)]], {}),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Refobe LLC",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    43: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the country logo",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("heading", 42),
                                ("image", 43),
                            ]
                        ],
                        {},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {"label": "Images"}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("logos", 45),
                            ]
                        ],
                        {},
                    ),
                    47: ("wagtail.blocks.RichTextBlock", (), {}),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": True},
                    ),
                    49: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Photo", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Role / Job Title",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Bio", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "LinkedIn Page", "required": False},
                    ),
                    53: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Twitter Page", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 48),
                                ("image", 49),
                                ("role", 50),
                                ("description", 51),
                                ("linkedin", 52),
                                ("twitter", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.ListBlock",
                        (54,),
                        {"label": "Team Members", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("members", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "deafult": "Traveller,CEO",
                            "help_text": "Any subtitle realted to the person",
                            "label": "Role",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (None, "No rating"),
                                (0, "0 Stars"),
                                (1, "1 Star"),
                                (2, "2 Stars"),
                                (3, "3 Stars"),
                                (4, "4 Stars"),
                                (5, "5 Stars"),
                            ],
                            "icon": "pick",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("image", 26),
                                ("button", 27),
                                ("role", 57),
                                ("stars", 58),
                            ]
                        ],
                        {},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("testimonials", 60),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Content Section",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    ("article_section", 2),
                    ("contact_section", 14),
                    ("faq_section", 23),
                    ("faq_image_section", 30),
                    ("feature_section", 32),
                    ("feature_row_section", 36),
                    ("feature_carousel_section", 39),
                    ("hero_section", 41),
                    ("hero_section_carousel", 41),
                    ("hero_slide_section", 41),
                    ("logo_cloud_section", 46),
                    ("richtext_section", 47),
                    ("team_section", 56),
                    ("testimonial_section", 61),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "From the blog",
                            "help_text": "Add a title",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Learn how to grow your business with our expert advice",
                            "help_text": "Add a description",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Ready To Take The Next Step?",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details. Keep it meaningful!",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write your address",
                            "label": "Location 1",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Country and district",
                            "label": "Location 2",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write Number",
                            "label": "Phone Number",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Write email",
                            "label": "Email",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Text", "max_length": 100, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "If provided, the button will be a link to this URL",
                            "label": "Link",
                            "null": True,
                            "required": False,
                        },
                    ),
                    11: (
                        "main.blocks.helper_blocks.APIPageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("description", 4),
                                ("location1", 5),
                                ("location2", 6),
                                ("phone", 7),
                                ("email", 8),
                                ("button", 13),
                            ]
                        ],
                        {},
                    ),
                    15: ("main.blocks.common_blocks.TagsBlock", (), {"label": "Tag"}),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "We are the best", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the best of both worlds. Enjoy comfortable accommodations paired with thrilling outdoor activities in a breathtaking natural setting.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Add a simply worded question, like 'How much will it cost?'",
                            "label": "Question",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Provide a short answer in no more than a few lines of text",
                            "label": "Answer",
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {
                            "help_text": "Add a link to be followed for more information on that question, feature or product",
                            "label": "Button",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 18), ("answer", 19), ("button", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {"label": "FAQs"}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("faqs", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Debugging Tech and Staffing Glitches",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    26: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Hero image", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 9),
                                ("link", 10),
                                ("page", 11),
                                ("button_type", 12),
                            ]
                        ],
                        {"label": "Call To Action", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("image", 26),
                                ("button", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {"label": "FAQs", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("faqs", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (28,), {"label": "Features"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("features", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "This is the paragraph where you can write more details about your product. Keep it meaningful!",
                            "label": "Long Description",
                            "required": False,
                        },
                    ),
                    34: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the side panel of a feature list",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    35: ("wagtail.blocks.ListBlock", (28,), {"label": "Feature Rows"}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("long_description", 33),
                                ("image", 34),
                                ("features", 35),
                            ]
                        ],
                        {},
                    ),
                    37: ("main.blocks.helper_blocks.APIImageChooserBlock", (), {}),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {"label": "Image Carousel"},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("images", 38),
                                ("button", 27),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("image", 26),
                                ("button", 27),
                            ]
                        ],
                        {"label": "Content", "required": True},
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("content", 40)]], {}),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Refobe LLC",
                            "help_text": "Add a heading at the beginning of this page section",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    43: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Pick an image for the country logo",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("heading", 42),
                                ("image", 43),
                            ]
                        ],
                        {},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {"label": "Images"}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("logos", 45),
                            ]
                        ],
                        {},
                    ),
                    47: ("wagtail.blocks.RichTextBlock", (), {}),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": True},
                    ),
                    49: (
                        "main.blocks.helper_blocks.APIImageChooserBlock",
                        (),
                        {"label": "Photo", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Role / Job Title",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Bio", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "LinkedIn Page", "required": False},
                    ),
                    53: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Twitter Page", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 48),
                                ("image", 49),
                                ("role", 50),
                                ("description", 51),
                                ("linkedin", 52),
                                ("twitter", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.ListBlock",
                        (54,),
                        {"label": "Team Members", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("members", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "deafult": "Traveller,CEO",
                            "help_text": "Any subtitle realted to the person",
                            "label": "Role",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (None, "No rating"),
                                (0, "0 Stars"),
                                (1, "1 Star"),
                                (2, "2 Stars"),
                                (3, "3 Stars"),
                                (4, "4 Stars"),
                                (5, "5 Stars"),
                            ],
                            "icon": "pick",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("description", 25),
                                ("image", 26),
                                ("button", 27),
                                ("role", 57),
                                ("stars", 58),
                            ]
                        ],
                        {},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tag", 15),
                                ("title", 16),
                                ("description", 17),
                                ("testimonials", 60),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Content Section",
            ),
        ),
    ]
